@echo off
setlocal enabledelayedexpansion

set DEVICE=RMX3761
set VENDOR=realme
set VENDOR_PATH=..\..\..\vendor\%VENDOR%\%DEVICE%

echo.
echo "Generating Android.bp..."
(
echo // Automatically generated file. DO NOT MODIFY
echo //
echo // This file is generated by device/%VENDOR%/%DEVICE%/setup-makefiles.bat
echo.
echo soong_namespace {
echo }
echo.
echo android_app_import {
echo     name: "RealmeSAU",
echo     owner: "%VENDOR%",
echo     apk: "proprietary/system_ext/app/RealmeSAU/RealmeSAU.apk",
echo     certificate: "platform",
echo     dex_preopt: {
echo         enabled: false,
echo     },
echo     system_ext_specific: true,
echo }
echo.
echo android_app_import {
echo     name: "RealmeOTA",
echo     owner: "%VENDOR%",
echo     apk: "proprietary/system_ext/app/RealmeOTA/RealmeOTA.apk",
echo     certificate: "platform",
echo     dex_preopt: {
echo         enabled: false,
echo     },
echo     system_ext_specific: true,
echo }
) > %VENDOR_PATH%\Android.bp

echo.
echo "Generating Android.mk..."
(
echo # Automatically generated file. DO NOT MODIFY
echo #
echo # This file is generated by device/%VENDOR%/%DEVICE%/setup-makefiles.bat
echo.
echo LOCAL_PATH := $(call my-dir^)
echo.
echo ifeq ($(TARGET_DEVICE^),%DEVICE%^)
echo.
echo include $(CLEAR_VARS^)
echo LOCAL_MODULE := libcamera_client
echo LOCAL_MODULE_OWNER := %VENDOR%
echo LOCAL_SRC_FILES := proprietary/system/lib64/libcamera_client.so
echo LOCAL_MODULE_PATH := $(TARGET_OUT_SYSTEM_SHARED_LIBRARIES^)
echo LOCAL_MODULE_TAGS := optional
echo LOCAL_MODULE_SUFFIX := .so
echo LOCAL_MODULE_CLASS := SHARED_LIBRARIES
echo include $(BUILD_PREBUILT^)
echo.
echo include $(CLEAR_VARS^)
echo LOCAL_MODULE := audio.primary.ums9230
echo LOCAL_MODULE_OWNER := %VENDOR%
echo LOCAL_SRC_FILES := proprietary/vendor/lib64/hw/audio.primary.ums9230.so
echo LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR_SHARED_LIBRARIES^)/hw
echo LOCAL_MODULE_TAGS := optional
echo LOCAL_MODULE_SUFFIX := .so
echo LOCAL_MODULE_CLASS := SHARED_LIBRARIES
echo include $(BUILD_PREBUILT^)
echo.
echo endif
) > %VENDOR_PATH%\Android.mk

echo.
echo "Generating device-vendor.mk..."
(
echo # Automatically generated file. DO NOT MODIFY
echo #
echo # This file is generated by device/%VENDOR%/%DEVICE%/setup-makefiles.bat
echo.
echo # APEX packages
echo PRODUCT_PACKAGES += \
echo     RealmeSAU \
echo     RealmeOTA
echo.
echo # Shared libraries
echo PRODUCT_PACKAGES += \
echo     libcamera_client \
echo     audio.primary.ums9230
) > %VENDOR_PATH%\%DEVICE%-vendor.mk

echo.
echo "Done!"
